"""
Financial Fraud Detection System — Dashboard Entry Point
=========================================================

Main Streamlit application that serves as the home page of the
multi-page financial fraud detection dashboard. Sub-pages are
automatically discovered from the ``app/pages/`` directory by
Streamlit's native multipage architecture.

Launch with:
    streamlit run app/streamlit_app.py
"""

import sys
from pathlib import Path

import streamlit as st

# ---------------------------------------------------------------------------
# Project root resolution
# ---------------------------------------------------------------------------
# app/streamlit_app.py  ->  app/  ->  financial-fraud-detection/
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Ensure project root is on sys.path (needed for ``src.transformers``)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Local imports (after sys.path setup)
from app.ui import (  # noqa: E402
    APP_TITLE,
    APP_VERSION,
    PAGES,
    footer,
    page_header,
    section_heading,
    status_indicator,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MODEL_PATH = PROJECT_ROOT / "models" / "final_xgboost_pipeline.joblib"
DATA_PATH = PROJECT_ROOT / "data" / "raw"

# ---------------------------------------------------------------------------
# Page configuration (must be the first Streamlit command)
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title=APP_TITLE,
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Minimal custom CSS for consistent professional appearance
# ---------------------------------------------------------------------------
st.markdown(
    """
    <style>
    /* Tighten main content spacing */
    .block-container { padding-top: 2rem; }
    /* Sidebar heading */
    [data-testid="stSidebar"] [data-testid="stMarkdown"] h3 {
        font-size: 0.9rem;
        color: #6c757d;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Sidebar — branding & navigation info
# ---------------------------------------------------------------------------
with st.sidebar:
    st.markdown("## 🛡️ Fraud Detection")
    st.caption(f"v{APP_VERSION}")
    st.divider()
    st.markdown("### Navigation")
    st.markdown(
        "Use the pages listed below to explore different "
        "aspects of the fraud detection analysis."
    )
    st.divider()

    # Quick-reference page index
    for key, page in PAGES.items():
        st.markdown(f"{page['icon']}  {page['title']}")

    st.divider()
    st.caption("Built with Streamlit · XGBoost · scikit-learn")

# ---------------------------------------------------------------------------
# Model loading (cached)
# ---------------------------------------------------------------------------

@st.cache_resource(show_spinner="Loading fraud detection model …")
def load_model():
    """
    Load the serialized XGBoost pipeline from disk.

    Returns
    -------
    pipeline : sklearn.pipeline.Pipeline | None
        The loaded pipeline, or ``None`` if loading fails.
    error_msg : str | None
        A human-readable error description, or ``None`` on success.
    """
    import joblib

    if not MODEL_PATH.exists():
        return None, (
            f"Model file not found at expected path:\n"
            f"`{MODEL_PATH.relative_to(PROJECT_ROOT)}`\n\n"
            f"Please ensure the model artifact has been generated by "
            f"running notebook `09_model_serialization.ipynb`."
        )

    try:
        pipeline = joblib.load(MODEL_PATH)
        return pipeline, None
    except Exception as exc:
        return None, (
            f"Failed to deserialize model:\n\n"
            f"**{type(exc).__name__}**: {exc}"
        )


# ---------------------------------------------------------------------------
# Main page content
# ---------------------------------------------------------------------------
page_header(
    APP_TITLE,
    "Machine-learning-powered financial transaction fraud detection "
    "and analytics dashboard.",
)

# ---------------------------------------------------------------------------
# System status
# ---------------------------------------------------------------------------
section_heading("System Status")

pipeline, load_error = load_model()

col_model, col_data, col_runtime = st.columns(3)

with col_model:
    if load_error is None:
        status_indicator("Model", "ok", "XGBoost pipeline loaded")
    else:
        status_indicator("Model", "error", "Failed to load")

with col_data:
    dataset_exists = any(DATA_PATH.glob("*.csv")) if DATA_PATH.exists() else False
    if dataset_exists:
        status_indicator("Dataset", "ok", "Available")
    else:
        status_indicator("Dataset", "warning", "Not found")

with col_runtime:
    status_indicator(
        "Runtime", "ok",
        f"Python {sys.version_info.major}.{sys.version_info.minor}"
    )

st.markdown("")  # spacing

# ---------------------------------------------------------------------------
# Model details
# ---------------------------------------------------------------------------
if load_error is None:
    section_heading("Model Details")

    detail_cols = st.columns(3)
    with detail_cols[0]:
        st.markdown("**Algorithm**")
        st.code("XGBoost", language=None)
    with detail_cols[1]:
        st.markdown("**Artifact**")
        st.code("final_xgboost_pipeline.joblib", language=None)
    with detail_cols[2]:
        st.markdown("**Pipeline Steps**")
        st.code(str(len(pipeline.steps)), language=None)

    with st.expander("Pipeline Architecture"):
        for i, (name, step) in enumerate(pipeline.steps, 1):
            st.markdown(f"{i}. **{name}** — `{type(step).__name__}`")
else:
    st.error("Model could not be loaded.", icon="🚨")
    st.warning(load_error)

# ---------------------------------------------------------------------------
# Dashboard overview
# ---------------------------------------------------------------------------
st.markdown("")
section_heading("Dashboard Sections")
st.markdown(
    "Navigate to each section using the sidebar pages for detailed analysis."
)

# Display page cards in a 3×2 grid
row1 = st.columns(3)
row2 = st.columns(3)
grid = row1 + row2

page_list = list(PAGES.values())
for i, col in enumerate(grid):
    if i < len(page_list):
        page = page_list[i]
        with col:
            st.markdown(
                f"**{page['icon']}  {page['title']}**\n\n"
                f"_Coming in next dashboard step_"
            )

# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------
footer()
